### ISSUE TITLE
Support namespaces

### ISSUE THREAD

**Issue by Crusader4Christ** [paroi-tech/typeonly#6]
```
export namespace iNames {
  export interface i1 {
    id: number;
    name: string;
  }
}
```
parsed to `{}`

**Comment by paleo** [comment]
Hi. It seems weird to me to export pure types from namespaces, because namespaces in TypeScript exist at runtime. I don't use namespaces, and I haven't implemented anything for them. I'm staying open and I might change my mind, but for now I suggest not using them.
