### ISSUE TITLE
Is there an API to iterate Interface properties?

### ISSUE THREAD

**Issue by lxgreen** [paroi-tech/typeonly#8]
Hey, thanks for this lib!

I have a question -- how can i traverse the interface properties? Currently I'm just checking the kind, cast the namedType to Interface and then get the Properties, so it's very verbose. I'd appreciate something like `literals`, but for properties

**Comment by paleo** [comment]
Hi. Yes I could add a helper for that, I will consider it.

I suggest to do something like:

```ts
const { loadModules, literals } = require("@typeonly/loader");

const modules = loadModules({
  bundle: require(`./types.to.json`)
});

const { MyType } = modules["./drawing"].namedTypes;
if (MyType.kind === "interface") {
  console.log("Properties:", MyType.properties);
}
```

After you test that `kind` is set to `"interface"`, you can explore the properties.
